### PR TITLE
fix grafana apt-get issue due to old version

### PR DESCRIPTION
**Pull request by wahlfeld**

### CODE REVIEW

**Comment by olix0r** [comment]
cc @siggy

**Comment by wahlfeld** [comment]
Issue here: https://github.com/linkerd/linkerd-examples/issues/246

**Comment by siggy** [comment]
@wahlfeld After a bit more thought I figured it was best to merge this as-is, to at least get the build working. I'm going to file a subsequent ticket around the comment I wrote up in this ticket.

**Comment by wahlfeld** [comment]
Thanks mate. Admittedly I wasn't too sure how to go about your suggestion
anyway lol.

**Pull request merged**
